2018-11-11 11:48:09.935 -06:00 [INF] {"Id":null,"CreationTimestamp":"0001-01-01T00:00:00.0000000","ApplicationName":"Pioneer Logs","ApplicationLayer":"Pioneer.Logs.Samples.AspNetCore","ApplicationLocation":"/api/exception","Message":null,"Hostname":"DESKTOP-NOMUMK6","UserId":"","UserName":"","PerformanceElapsedMilliseconds":null,"Category":null,"Exception":{"Message":"Force Exception","Data":[],"InnerException":null,"TargetSite":"Microsoft.AspNetCore.Mvc.ActionResult`1[System.Collections.Generic.IEnumerable`1[System.String]] Get()","StackTrace":"   at Pioneer.Logs.Samples.AspNetCore.Controllers.TestController.Get() in C:\\source\\pioneer-logs\\samples\\Pioneer.Logs.Samples\\Pioneer.Logs.Samples.AspNetCore\\Controllers\\TestController.cs:line 16\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Pioneer.Logs.Tubs.AspNetCore.PioneerLogsMiddleware.InvokeAsync(HttpContext httpContext) in C:\\source\\pioneer-logs\\src\\Pioneer.Logs\\Tubs\\AspNetCore\\PioneerLogsMiddleware.cs:line 31","HelpLink":null,"Source":"Pioneer.Logs.Samples.AspNetCore","HResult":-2146233088,"$type":"Exception"},"ExceptionMessage":"Force Exception","TraceId":"0HLI7VN91DHJD:00000001","AdditionalInfo":{"UserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"],"Languages":["en-US,en;q=0.9"]},"$type":"PioneerLog"}
